spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ismoil_0709
    url: jdbc:postgresql://localhost:5432/click_uz_payments
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
